languageCode: en-us
baseURL: "https://sindrekjelsrud.github.io/"
title: Sindre's Website
theme: PaperMod

enableInlineShortcodes: true
enableMoji: true # allowing using emoji
enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

paginate: 5 # articles per page

minify:
  disableXML: true
  # minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Sindre Kjelsrud
  description: "Student"
  author: Sindre # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]

  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Home"

  assets:
    favicon: "img/cat.png"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Sindre Kjelsrud"
    subtitle: "Student at Western University of Applied Sciences"
    imageUrl: "img/me-myself-and-i.png"
    imageTitle: "Me, Myself and I"
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: Projects
        url: projects
      - name: Resume
        url: en_resume

  # home-info mode
  homeInfoParams:
    Title: "Welcome! üöÄ"
    Content: "My name is Sindre Kjelsrud, and I'm an IT-Student at Western University of Applied Sciences."

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/sindre-kjelsrud-345583218/"
    - name: github
      url: "https://github.com/SindreKjelsrud"
    - name: instagram
      url: "https://instagram.com/SindreKjelsrud"
    - name: spotify
      url: "https://open.spotify.com/user/kjelsrud!"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: resume
      name: Resume
      url: /en_resume/
      weight: 3
    - identifier: blog
      name: Blog
      url: /blog-posts/
      weight: 4
    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30

#########################################################################

#‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚††‚†§‚†í‚†í‚†í‚†í‚†í‚†§‚£Ñ‚°Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä
#‚†Ä‚†Ä‚†Ä‚†Ä‚¢Ä‚°≤‚¢ã‚†ù‚†ã‚£õ‚£≥‚°Ñ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†â‚†ì‚¢Ñ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä
#‚†Ä‚¢Ä‚††‚£¥‚†ó‚¢Ä‚†•‚†Ç‚¢Å‚†§‚†§‚†§‚†Å‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚£õ‚†õ‚†â‚†ó‚†í‚†≤‚¢§‚£Ä‚†Ä
#‚†∞‚†É‚†ê‚†Ä‚†ã‚°†‚†Ä‚†Æ‚†§‚†§‚†§‚†§‚°§‚°Ñ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢†‚£Ω‚†Ñ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢∏‚°Ü            __       __ 
#‚†Ä‚†ú‚†Ä‚†Ä‚†à‚†Ä‚¢†‚£§‚£î‚£í‚°í‚†í‚†Ç‚†Å‚†Ä‚°Ä‚¢Ä‚£Ä‚£§‚£∂‚£ø‚°ü‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢Ä‚°º‚†Ä           |  \     |  \
#‚†à‚†Ä‚†Ä‚†Ä‚†Ä‚£∞‚°ø‚†ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚†ø‚†ü‚†â‚†Å‚†Ä‚†Ä‚†Ä‚¢Ñ‚°¥‚†ã‚†Ä‚†Ä   _______ \‚ñì‚ñì ____| ‚ñì‚ñì
#‚†Ä‚†Ä‚†Ä‚†Ä‚£∞‚†ã‚†Ä‚†Ä‚†Ä‚†à‚†ô‚†õ‚†õ‚†õ‚†õ‚†ã‚†â‚†Ä‚†Ä‚†Ä‚†Ä‚¢Ä‚£†‚£¥‚°ä‚†Å‚†Ä‚†Ä‚†Ä‚†Ä   /       \  \/      ‚ñì‚ñì
#‚†Ä‚°†‚†ê‚†â‚¢∏‚£∂‚£Ñ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢Ä‚°Ä‚£§‚£∂‚£ø‚£ø‚£ø‚°ª‚°Ñ‚†Ä‚†Ä‚†Ä‚†Ä  |  ‚ñì‚ñì‚ñì‚ñì‚ñì‚ñì‚ñì ‚ñì‚ñì  ‚ñì‚ñì‚ñì‚ñì‚ñì‚ñì‚ñì
#‚†Ä‚†Å‚†Ä‚†Ä‚£ø‚¢π‚£ø‚£ø‚£ø‚£∂‚£¶‚£∂‚£∂‚£∂‚£∂‚£∂‚£ô‚†ã‚†¥‚†õ‚£ø‚¢õ‚°ø‚†¨‚†É‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä  \‚ñì‚ñì    \| ‚ñì‚ñì ‚ñì‚ñì  | ‚ñì‚ñì
#‚†Ä‚†Ä‚†Ä‚†Ä‚†à‚†ò‚†π‚£ø‚£ø‚†õ‚†õ‚†õ‚¢ø‚°á‚†Ä‚†â‚†Ä‚†ò‚†â‚¢∞‚£Ø‚°ä‚†ô‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä   _\‚ñì‚ñì‚ñì‚ñì‚ñì‚ñì\ ‚ñì‚ñì ‚ñì‚ñì__| ‚ñì‚ñì
#‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†à‚†±‚°Ñ‚†Ä‚†Ä‚†ò‚†É‚†Ä‚†Ä‚†Ä‚†Ä‚††‚†õ‚†Ä‚†Å‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä    |       ‚ñì‚ñì ‚ñì‚ñì\‚ñì‚ñì    ‚ñì‚ñì
#‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢π‚¢≤‚£Ñ‚†Ä‚†í‚†Ç‚†Ä‚£Ä‚¢¥‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä     \‚ñì‚ñì‚ñì‚ñì‚ñì‚ñì‚ñì \‚ñì‚ñì \‚ñì‚ñì‚ñì‚ñì‚ñì‚ñì‚ñì
#‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚£Ä‚£Ä‚£Ä‚£Ä‚£à‚†Ä‚¢ª‚£ø‚£∂‚£¥‚£æ‚°ü‚¢∏‚£Ä‚£Ä‚£Ä‚£Ä‚£Ä‚£Ä‚°Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä
#‚†Ä‚†Ä‚†Ä‚¢Ä‚°é‚†Ä‚¢Ä‚£†‚°§‚†Ç‚¢†‚†à‚¢ø‚£ø‚°ø‚£ø‚†É‚†Ä‚†ô‚£Ä‚£Ä‚£Ä‚°Ä‚†Ä‚†ô‚£Ñ‚†Ä‚†Ä‚†Ä‚†Ä
#‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢†‚†â‚†â‚¢á‚†Ä‚†à‚°á‚†ò‚£è‚†Ä‚°ø‚°∞‚†Ä‚†Ä‚¢Ä‚†õ‚†õ‚†ª‚£Ü‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä
#‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢∏‚†â‚†â‚†â‚†ó‚†í‚¢ø‚°Ä‚†∏‚°à‚£†‚†ß‚†û‚†â‚°è‚†â‚†â‚†â‚¢π‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä
#‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†∏‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Å‚†Ä‚†â‚†â‚†Ä‚†Ä‚†à‚†Ä‚†Ä‚†Ä‚†Ä‚†∏‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä

#########################################################################